### ISSUE TITLE
OSX - Open Project and all options greyed out, can't change.

### ISSUE THREAD

**Issue by Blatman** [jyapayne/Web2Executable#90] opened 2015-10-30 19:55 UTC
OSX Mavericks 10.9.5 using W2E 0.2.7b
This happens if opening a project that has already been exported at some stage.
The cause is the package.json file has references to icons but if the icons no longer exist in the app folder the greyed out problem will occur. If the references in the package.json file are removed or the images are placed back in the app folder everything will be OK and W2E will be changeable
(W2E appears to place the icon images into the app folder according to the package.json settings which are set via W2E at each export).
Not a problem once you know.

Edit:  Was OK with 0.2.4b but also occurs with 0.2.6b

Cheers,

Blane

**Comment by jyapayne** [comment] 2015-11-01 15:08
Hmm, I tested your description of the issue by opening a project, exporting it, closing W2E, deleting the icon file, then opening up W2E again and opening the project. I get the expected result of a red outlined field indicating that the icon is missing.

Can you whip up a sample project with directions on how to reproduce?

**Comment by Blatman** [comment] 2015-11-01 17:55
Hi Joey, 
knocked up a wee test project - the icons have been deleted from the AppFolder but still in the package.json, if references are removed from json then will be able to use W2E.
Sent to email as a zip.

Note: I have been getting weird stuff happening whilst generating the test project - tried exporting and no packages generated under the Export folder, found them under a folder called files in the original build folder even though I had specified a completely different folder. Trying to use AppCleaner to clean any histories, etc associated with W2E. If you still can't get the issue with this project maybe I have some weird cache issues or something although it happens both on Mavericks and Yosemite.

Cheers

**Comment by jyapayne** [comment] 2015-11-03 00:36
Thanks for the zipped project :) It turned out to be an issue with logging, strangely enough. The location of the error log file was wrong for reporting errors with file misplacement and caused a freeze. 

Can you try this version out? http://www.mediafire.com/download/dvdaccnd868ypdd/Web2ExeMac-v0.2.8b.zip

**Comment by Blatman** [comment] 2015-11-03 17:37
Hi Joey,

the 2.8b load fixes the greyed out problem OK (tried on Mavericks).

Note: still having problem with exporting generated folder is empty but partially built files all end up in files folder under User/<user>/Library/Application Support/Web2Executable/files - I'll send the error.log to your email FYI.

Cheers,

Blane

**Comment by jyapayne** [comment] 2015-11-03 18:10
Ah, from your error.log file, there seems to be at least one broken symlink in your node_modules folder. This can happen if you manually remove a node dependency with `rm -rf` instead of `npm uninstall <module-name>`. From the error, it looks like the offending file is `node_modules/.bin/os-name`. Try removing it and see if it helps :)

**Comment by Blatman** [comment] 2015-11-03 18:29
Very good Joey - worked a treat. Looks like I'll have to be more disciplined in managing the node-modules folder.

Cheers.

**Comment by jyapayne** [comment] 2015-11-03 19:28
Cool :) Glad to help!

**Closed by jyapayne** 2015-11-03 19:28 UTC
