### ISSUE TITLE
[OSX] Mac Icon not showing if project re-opened

### ISSUE THREAD

**Issue by Blatman** [jyapayne/Web2Executable#72] opened 2015-07-25 06:08 UTC
May not be relevant if the UI is being redesigned but noticed that Mac Icon is shown OK on new project however if project is re-opened the icon is missing.
New project will create mac_icon in package.json and work OK but on re-open W2E is looking for mac_app_icon in package.json - it works if mac_icon entry is altered to mac_app_icon.
The mac icon selection box appears keyed to mac_icon in the package.json manifest.

Tested: OSX Mavericks 10.9.5/W2E 0.2.4b

**Comment by jyapayne** [comment] 2015-07-25 17:06
The redesign has already been done :) 0.2.4b has the redesign already.

I'm not quite sure what you mean. Is the icon missing inside W2E or inside the generated app when you open it for the second time?

**Comment by Blatman** [comment] 2015-07-25 19:20
It is the Mac Icon box in the W2E header panel - see attached graphics
SS-1  Initial project and exported
SS-2  W2E re-opened using File Project History (blank)
SS-3  mac_app_icon added and mac_icon = "" to show icon.


![ss-1](https://cloud.githubusercontent.com/assets/11089335/8890889/8a462686-3309-11e5-8f40-00c02ee6f1d9.jpg)
![ss-2](https://cloud.githubusercontent.com/assets/11089335/8890888/8a3e8732-3309-11e5-92d5-39576ff24f13.jpg)
![ss-3](https://cloud.githubusercontent.com/assets/11089335/8890890/8a4eb5da-3309-11e5-8fbd-5a589bacb66a.jpg)

**Comment by jyapayne** [comment] 2015-07-26 00:37
Ah, yes, that is some strange behaviour, thank you for the pictures. This is really strange, since I follow your steps exactly and don't seem to have an issue, and I have no mention of "mac_app_icon" in my code. But I'll give it a more in depth look to see what's up :)

Also, you can use a png in the Mac Icon field and W2E will convert it to icns for you. Pngs tend to work well with the app.

**Comment by Blatman** [comment] 2015-07-26 06:58
Yes, indeed it is strange - I only came across the mac_app_icon when I was checking out the package.json at an earlier date just after the feature had been introduced. Almost as if something in the code is inserting the default app folder into the mac_icon parameter at some stage.
Just tried using png instead of icns and appears to be OK so only an issue if icns used - not a showstopper anyway.
Cheers,
Blane

**Comment by jyapayne** [comment] 2015-09-28 01:07
Can't reproduce this, and it's been quite a while. Closing for now.

**Closed by jyapayne** 2015-09-28 01:07 UTC
