### ISSUE TITLE
Export = empty folder ?

### ISSUE THREAD

**Issue by Inateno** [jyapayne/Web2Executable#103] opened 2015-11-24 21:23 UTC
Hi, I'm back ^^

Have a problem, maybe it's only with the last version I'll try more tomorrow.
I click export and when it's "done" I have nothing in my output folder except an empty folder (with the name of my app).

Any idea ?
It's a new app, the first export did well but second nop and still not working.

**Comment by jyapayne** [comment] 2015-11-24 21:40
Hey :)

See #80. Basically, there might be some issue with the path limit on Windows if you have a deeply nested node_modules folder. That's the most common reason, anyway. Other than that, if you happened to delete a node module without using "npm uninstall <module-name>", there might be a hidden link in the node_modules folder that is blank.

Is there anything inside the error.log?

**Comment by Inateno** [comment] 2015-11-25 08:57
There is no npm folder on this project, I don't need any npm in production and the folder is a new one "project/release/exe/in" with a /out folder in /exe.

Maybe creating an empty npm folder ?
I'll try and check the log.

**Comment by Inateno** [comment] 2015-11-25 20:08
Cannot found any error.log file :(
I try on an other computer

**Comment by jyapayne** [comment] 2015-11-25 21:04
Hmm, there should **always** be an error.log file located here: C:\Users<YourUser>\AppData\Local\Web2Executable\Web2Executable\files

If there isn't, then something is wrong.

**Comment by Inateno** [comment] 2015-11-25 21:19
Ah yes thank you !

```

Getting versions...
INFO       2015-11-25 22:11:08,237 command_line.py: 393 get_versions - Getting versions...
Loading package.json
INFO       2015-11-25 22:14:39,930 command_line.py: 458 load_package_json - Loading package.json
Loading package.json
INFO       2015-11-25 22:14:39,931 command_line.py: 458 load_package_json - Loading package.json
Traceback (most recent call last):
  File "<string>", line 59, in run
  File "C:\Users\Joey\Downloads\Web2Executable\build\Web2Exe\out00-PYZ.pyz\command_line", line 796, in make_output_dirs
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 42: ordinal not in range(128)

ERROR      2015-11-25 22:14:46,438 command_line.py: 87 my_excepthook - Traceback (most recent call last):
  File "<string>", line 59, in run
  File "C:\Users\Joey\Downloads\Web2Executable\build\Web2Exe\out00-PYZ.pyz\command_line", line 796, in make_output_dirs
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 42: ordinal not in range(128)

```

That's funny, it's not my path, maybe this is causing the error ?

For this last error I created a new folder "test" with an index.html inside and only a "<h1>Hello world</h1>" in the basic html structure.

Also we should add an "error" tracking message on the GUI because I get a "Done!" instead of "error".

**Comment by jyapayne** [comment] 2015-11-25 21:27
Haha, it's funny you should say that about the error. It looks like the error is in response to an error trying to be thrown by the GUI. I'll post a version in this issue a bit later that hopefully will point out the exact issue after you run it again. However, it looks like a Unicode error of some kind. Do you have any unicode characters in your path?

**Comment by Inateno** [comment] 2015-11-25 21:42
Last project path: T:\Gits\test
Export to "output"

All default values...

Ho wait, there is unicode in the path where web2exe is located, I move it somewhere else.

**Comment by Inateno** [comment] 2015-11-25 21:54
No change :( I did a new project with a file encoded as UTF-8 but same error :(
And on my other computer (but same windows user) it's not working too.

That's pretty weird, it was working :/ I try older versions.

**Comment by jyapayne** [comment] 2015-11-25 23:10
Can you try out [this version?](http://www.mediafire.com/download/96go2zkhjfj9t1u/Web2ExeWin-v0.3.3b.zip)

**Comment by Inateno** [comment] 2015-11-26 11:14
It's Working !
First shot I changed export to "output" value => OK
Second shot I selected the folder with the button (and complete path appear) => OK

Thank you :)

**Comment by jyapayne** [comment] 2015-11-27 02:19
You're welcome! The release with this fix is out now!

**Comment by williamd1k0** [comment] 2016-01-24 01:41
I am having the same problem (and the same traceback), but rather was exporting normally for win32.
I tried other output paths and another version of nw.js and still the same problem.
Version: `0.3.4.3b`
OS: `Windows 10`

```python-traceback
Traceback (most recent call last):
  File "<string>", line 130, in run
  File "C:\Users\Joey\Downloads\Web2Executable\build\Web2Exe\out00-PYZ.pyz\command_line", line 805, in make_output_dirs
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 27: ordinal not in range(128)

ERROR      2016-01-23 23:23:16,335 command_line.py: 97 my_excepthook - Traceback (most recent call last):
  File "<string>", line 130, in run
  File "C:\Users\Joey\Downloads\Web2Executable\build\Web2Exe\out00-PYZ.pyz\command_line", line 805, in make_output_dirs
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 27: ordinal not in range(128)
```

**Comment by jyapayne** [comment] 2016-01-24 04:40
Hmmm, it seems like a regression. The issue is still unicode characters in your project path. To workaround it for now, either try the version I linked above, or remove any unicode characters. I'll try to fix it ASAP.

**Comment by williamd1k0** [comment] 2016-01-24 06:20
Then, I was hours here trying to figure out what was going on and I finally understood what it was.

Using the version `0.3.3b` he also gave error. But the traceback before said unicode character error because it was trying to show a Windows Error that contained unicode characters (accentuation for  Brazilian Portuguese).

![2016-01-24 04_12_07-central de acoes](https://cloud.githubusercontent.com/assets/10428035/12534812/e92dc3da-c250-11e5-94ee-5c26262b02c2.png)

The error in question would "*Unable to create an existing file*" (N**ã**o **é** poss**í**vel criar um arquivo j**á** existente) on the path `%temp%\webexectemp\`

I checked the folder and had some of my project files there. I deleted the content and tried again and it worked.

But then continued the folder with the same problem, these files are not deleted after finishing the export. Detail, the files that were there have the property "read only".

That's all, I hope this information can help improve the program because I like it very much, great job! :+1:

**Comment by jyapayne** [comment] 2016-01-24 18:33
Thank you for investigating! Python 2.7's unicode support is not that good and issues like this keep appearing. I'm going to try switching my code over to use Python 3, which has much better unicode support and hopefully it will eliminate these issues with getting errors about displaying errors.

As for the *actual* issue, it looks like that directory is not being properly deleted from what you've investigated. Should be a quick fix :)

**Comment by jyapayne** [comment] 2016-01-25 13:51
@williamd1k0 What permission level do you have on your system? It looks like the issue may be caused by a permission issue, since I am deleting the folder after it has been created, but there appears to be an error in deleting it. If you run Web2Exe as administrator, does the same behaviour persist?

**Comment by jyapayne** [comment] 2016-01-25 14:10
@williamd1k0 Can you try out [this version](https://github.com/jyapayne/Web2Executable/releases/download/v0.3.4.4b/Web2ExeWin-Setup.zip) and see if it fixes your issue?

**Comment by williamd1k0** [comment] 2016-01-25 17:42
I have full access administrator, including the Temp folder.

Before testing this version, I tried again as administrator and the program is closing for no reason, staying open for a few seconds. Did not show any error in the log or notification, only crashed instantly.

I tried re-run normally and not opened. I tried this version and the same thing happened. I tried to run on another computer and opened normally, but continues with the problem not delete read-only files.

Then I tried to run the source code and functioned normally but with the current problem.

I believe that some other error is being hidden by a problem of windows characters.

Running at source-code, the following message appears: `libpng warning: iCCP: known incorrect sRGB profile`

**Comment by jyapayne** [comment] 2016-01-26 00:40
You are correct. The main issue is probably hidden by this unicode problem. I've updated Web2Exe to use Python 3.4, which has much better unicode support. Try [this version](https://github.com/jyapayne/Web2Executable/releases/download/v0.3.4.4b/Web2ExeWin-Setup-Py3.zip) and tell me how it goes!

**Comment by williamd1k0** [comment] 2016-01-26 02:26
Now the program is opening normally and shows the error of temporary files not deleted with the correct accent.

![2016-01-26 00_21_46-central de acoes](https://cloud.githubusercontent.com/assets/10428035/12570897/e76cf3b8-c3c2-11e5-9983-89a94420da07.png)

Now you just need to know why the temporary folder is not being deleted. Of course I could just disable the read-only property of the files on it, but risk happens again with others.

**Comment by jyapayne** [comment] 2016-01-26 05:37
Yeah, it's a mystery to me since the program had the ability to create the directory, it should be able to delete it. I'll have to look at it more and maybe I can figure it out.

**Comment by jyapayne** [comment] 2016-01-26 14:28
Where is your original project folder (Fuquest) and what are the permissions on that in the "Security" tab of the properties window for that folder? There's something weird either with that folder or with the one I'm creating. Can you also check the permissions for the ```webexetemp``` directory? 

By the way, thank you for helping debug the issue! :)

**Comment by williamd1k0** [comment] 2016-01-26 17:45
Well, in the project folder appears a "user" who do not quite know what it means and it does not have all permissions.

![2016-01-26 15_15_49-propriedades de fuquest](https://cloud.githubusercontent.com/assets/10428035/12589059/fd6b9e96-c442-11e5-9d37-7e7fef605121.png)

On the other hand, the temporary folder have all permissions, apparently.

![2016-01-26 15_30_45-propriedades de webexectemp](https://cloud.githubusercontent.com/assets/10428035/12589144/7757768a-c443-11e5-8d78-f16351be28d4.png)

**Comment by jyapayne** [comment] 2016-01-26 19:39
Looks like we may be getting somewhere. What happens if you move your project folder to a different location (such as the root of the C:// drive), delete the ```webexetemp``` folder and then open the new location with Web2Exe and export a few times? I suspect that maybe the HomeUser (which is part of the HomeGroup if you have one set up) is messing with the permissions. So copy the folder to a location that is not part of the HomeGroup (anything except Pictures, Documents, Videos and Music).

**Comment by williamd1k0** [comment] 2016-01-27 09:02
Sorry about the delay, I ended up running out of internet. Anyway, even changing the location of the folder I had the same problem. Since I was without internet, I took a look at some of my scripts and found a solution using the error callback and chmod.

The repository was already updated with the branch python3, so it was only test.
As I do not know if I put in `utils.py` or `command_line.py`, I did not open a pull request, then I'll let the code here.

```python
# tested in command_line.py
def remove_readonly(self, action, name, exc):
        try:
            os.chmod(name, stat.S_IWRITE)
            os.remove(name)
        except Exception as e:
            error = u'Failed to remove directory: {}.'.format(temp_dir)
            error += '\nError recieved: {}'.format(e)
            self.logger.error(error)
            self.output_err += error


# when you delete the folder
utils.rmtree(temp_dir, onerror=self.remove_readonly)
```

I hope this can help!

**Comment by jyapayne** [comment] 2016-01-27 15:53
Thank you for writing some code :) Unfortunately, I couldn't get it to work. Does this piece of code solve the problem for you? If I use it and modify my permissions on the project folder to not have write access, this code raises a permissions error because I don't have permission to change the permissions :)

**Comment by williamd1k0** [comment] 2016-01-27 16:55
Here it worked perfectly. Anyway, this seems like the best way to deal with read-only files. Disable the read-only property if it can not be excluded and try deleting again.

**Comment by jyapayne** [comment] 2016-01-27 21:27
Alright. If it works for you, that's good enough for me. I'll add it to the repo and pump out a new release a little later. Thanks for helping with this!

**Comment by williamd1k0** [comment] 2016-01-28 02:31
I thank you for providing and improving the program, and sorry for my poor English. 
Anything else just call me.

**Comment by jyapayne** [comment] 2016-01-28 22:54
Your english is not that bad :) 

It should be good to go now with the latest release 0.4.0b. Let me know if it doesn't work!

**Closed by jyapayne** 2016-01-28 22:54 UTC
