### ISSUE TITLE
packaged app extremely slow on virtualized windows machine

### ISSUE THREAD

**Issue by jonmulcahy** [jyapayne/Web2Executable#135] opened 2016-05-13 12:23 UTC
I think this has more to do with NW.JS than Web2Executable, but when I run my packaged app on my virtualized bootcamp partition using Parallels, it is extremely slow. It loads up fast as always, but then plays at about 1/4 of the normal speed. If i reboot into the bootcamp partition instead of using it virtualized, it runs fine.

anyone seen anything like this before?

**Comment by jyapayne** [comment] 2016-05-13 14:38
Yeah, I've noticed this as well. Are you using a game library? When I used phaser, this was definitely the case and it's just due to graphics drivers not being that good for virtual machines. All real machines I tested on were perfectly fine.

**Comment by jyapayne** [comment] 2016-05-26 22:23
I think this is expected behaviour. I'm closing the issue :)

**Closed by jyapayne** 2016-05-26 22:23 UTC
