### ISSUE TITLE
node js modules not working in Enigma Virtual Box

### ISSUE THREAD

**Issue by srinigudimella** [jyapayne/Web2Executable#158] opened 2016-08-10 21:13 UTC
I have created uncompressed package and compiled in to single exe using Enigma Virtual Box. After that when I run the exe, noticed that all node modules code is not working. Can you please suggest what configuration we need to use to make this work? Thank you.

**Comment by jyapayne** [comment] 2016-08-10 21:26
Can you please provide either your project or a minimal example project that produces this behaviour?

**Comment by srinigudimella** [comment] 2016-08-11 13:25
Here is the sample project code with boxed output exe.
https://we.tl/nD8XQuHHNv
Thank you.

**Comment by jyapayne** [comment] 2016-08-15 22:29
I'm not sure what the problem is. I loaded your boxed exe, and it came up fine. There was a message: "We could not authenticate with USB flash drive." but I assume that's normal? There's also an error in the console that you tried to run "getserial.bat" but it wasn't executed. What is the expected behavior?

**Comment by srinigudimella** [comment] 2016-08-17 07:14
Thank you for your reply. I am executing the .bat file to validate the project for the below conditions.
1. Whether the exe is running from USB drive or not.
2. Whether exe is running from the same provided USB drive or not. Authenticate serial number of USB. 
The issue is the node exec is not working. The nedb to track the analytics is not working. 

Note: If I make package with compressed one then it is working fine with enigma virtual box but it is not secure. I can open with winrar or 7zip to view all the source code.
One more issue is that it is taking time to open the exe because it is compressed one.
If we make the package with uncompressed one then it is secure with Virtual box and can't view the source files directly but node js is not working.
Can you please advise on this. Thank you.

**Comment by jyapayne** [comment] 2016-08-18 20:52
In "validatefn.js", on line 7, if you change `"getserial.bat"` to `"cmd.exe /c getserial.bat"`, does that change anything for you? I get identical behaviour from both the unboxed and boxed version when I make this modification.

**Comment by jyapayne** [comment] 2016-11-18 14:47
Closing this because it's likely the issue is with Enigma.

**Closed by jyapayne** 2016-11-18 14:47 UTC
