### ISSUE TITLE
Failed loading NodeJS modules

### ISSUE THREAD

**Issue by moazam1** [jyapayne/Web2Executable#19] opened 2015-01-07 16:05 UTC
Thanks @jyapayne for great work!

I am having trouble using your application. I have successfully created a windows package but now it says that modules are missing. All modules are inside the project directory. I have successfully tested app with node webkit. 

Can you please tell me how do I rectify this problem?

**Comment by moazam1** [comment] 2015-01-07 17:04
I just downgraded NW version to 0.11.3 and it worked fine for me. But now I am having another problem. The app freezes and doesn't work at all. I got same issue when I run app directly using node-webkit. When I remove `"nodejs": false` from package.json then app works fine. 

Any clue why is it behaving like that?

**Comment by jyapayne** [comment] 2015-01-07 18:15
Hi :)
Usually, that means you might be overwriting some nodejs functions in your JavaScript. However, I'm not certain on this. You could enable the toolbar and check the JavaScript console. It might give you a more complete error message.

**Comment by moazam1** [comment] 2015-01-07 19:06
Hello @jyapayne,

Thanks for the quick reply. You are right about the error. I am getting require is undefined. I have a following javascript which uses nodejs and javascript.

	var gui = require('nw.gui');
	var win = gui.Window.get();
	var clipboard = gui.Clipboard.get();

	global.$ = $;

	$(function(){
		$('.minimize-window').click(function(e){
			win.minimize();

		});
	});

It works fine with the node-webkit but I am getting an error when I use your app. Any hint how to fix this issue?

**Comment by jyapayne** [comment] 2015-01-07 19:28
Which version are you using, the command line app, or the GUI?

**Comment by jyapayne** [comment] 2015-01-07 19:34
Ah, it looks like I may have misinterpreted the field "node-main" in my application. In the GUI node-main is the "Alt. Nodejs" field. If you fill that field in with your javascript file, does it work?

**Comment by jyapayne** [comment] 2015-01-07 19:50
Hmm, the code you wrote works for me when I tested it. Can I ask, where are you putting that javascript?

**Comment by moazam1** [comment] 2015-01-07 22:26
I have sent you an email. Thanks

**Comment by jyapayne** [comment] 2015-01-09 22:16
Please update this issue @moazam1. Also, please use Github instead of my email for the back and forth so that others may potentially benefit from similar issues.

Cheers!

**Comment by jyapayne** [comment] 2015-01-12 17:29
I'm closing this issue since I can't reproduce it and you are not responding.

Cheers

**Closed by jyapayne** 2015-01-12 17:29 UTC
