### ISSUE TITLE
Built app for windows crashes when opening a video file

### ISSUE THREAD

**Issue by shivasj** [jyapayne/Web2Executable#18] opened 2014-12-19 14:38 UTC
Does embedded videos in the web app play by default or do i have to do anything special. The app works great otherwise but when i click on a video link (Video mp4 file is local to the app) the app crashes. 

Any thoughts?

**Comment by MarxGames** [comment] 2015-01-12 07:19
I believe the issue is still there. I'm using a prebuilt windows binary and it seems to mess up the ffmpegsumo file on all platforms when exporting. I'm correcting the issue with going to the download folder and manually copying the ffmpegsumo files for each platform to replace the exported one. Usually the size of exported ffmpegsumo file is twice the original in the downloads folder.

**Comment by jyapayne** [comment] 2015-01-12 07:33
Did you download the latest version? On v0.1.12b, this issue should be fixed. I have tested it with my sample apps and they seem to work. There was an issue on previous versions that caused the files to be copied in a weird way. I know there is no way to tell which version you are using (as per your previous issue #21 ) but please grab the latest. 

Right now, there is no support for proprietary codecs, so only the formats supported by node-webkit are supported here (ogg, webm, wav, etc). 

Let me know if this solves your issue. If it doesn't, we can discuss it further.

**Comment by MarxGames** [comment] 2015-01-12 12:20
Issue was solved!

**Comment by jyapayne** [comment] 2015-01-12 17:27
Awesome :)

**Closed by jyapayne** 2015-01-12 17:27 UTC
